import mongoose from "mongoose";

export default mongoose.model("Campaign", new mongoose.Schema({
    name: { type: String, required: true, unique: true },
    domain: { type: String, required: true, unique: true, index: true },
    cnpj: { type: String, default: "" },
    stateregistration: { type: String, default: "" },
    socialreason: { type: String, default: "" },
    type: { type: String, required: true, default: "cpa" },
    approval: { type: String, required: true, default: "auto", index: true },
    negotiation: { type: String, required: true, default: "session" },
    networkmargin: { type: String, Number: true, default: 0 },
    commission: { type: String, required: true, default: "percentage" },
    commissionfixed: { type: Number, required: true, default: 0 },
    commissionpercentage: { type: Number, required: true, default: 0 },
    commercialcommission: { type: Number, required: true, default: 0 },
    commissiondisplay: { type: String },
    cookievalue: { type: Number, required: true, default: 30 },
    cookiefactor: { type: String, required: true, default: "days" },
    paymentvalue: { type: Number, required: true, default: 30 },
    paymentfactor: { type: String, required: true, default: "days" },
    validation: { type: Number },
    status: { type: String, required: true, default: "capture", index: true },
    contacts: { type: Array, required: true, default: [] },
    categories: { type: Array, required: true, default: [] },
    channels: { type: Array, required: true, default: [] },
    users: { type: Array, default: [], required: true },
    geos: { type: Array, default: [], required: true },
    addresses: { type: Array, default: [], required: true },
    removetoquery: { type: Array, default: [], required: true },
    addtoquery: { type: Array, default: [], required: true },
    linktoredirect: { type: String, default: "" },
    whitelabel: { type: String, default: null, index: true },
    rules: { type: String, default: "" },
    logo: { type: String, default: "" },
    icon: { type: String, default: "" },
    updated: { type: Date, default: Date.now, required: true },
    visibility: { type: Boolean, default: false, required: true, index: true },
    apideeplink: { type: Boolean, default: false, required: true, index: true },
    inupdate: { type: Boolean, default: false, index: true },
    createuser: { type: Object, default: {} },
    updateuser: { type: Object, default: {} },
    rascore: { type: Number, default: "" },
    rasolvedperc: { type: Number, default: "" },
    rastatus: { type: String, default: "" },
    ceclevel: { type: Number, default: 0 },
    cecstar: { type: Number, default: 0 },
    ebit: { type: String, default: "" },
    ebitdeliverytime: { type: Number, default: 0 },
    ebitreturnpurchase: { type: Number, default: 0 },
    enabled: { type: Boolean, default: true, required: true, index: true }
}, {
    collection: "campaigns",
    timestamps: true
}));
