import mongoose from "mongoose";

export default mongoose.model("Feeds", new mongoose.Schema({
    label: { type: String, trim: true },
    campaign: { type: String, required: true },
    url: { type: String, trim: true },
    format: { type: String, required: true },
    rootfield: { type: String, trim: true },
    itemfield: { type: String, trim: true },
    linkroot: { type: String },
    compress: { type: String, trim: true },
    schedule: { type: String, required: true },
    timetable: { type: String },
    weeklyday: { type: String },
    dateday: { type: String },
    linktype: { type: String, required: true },
    redirectparam: { type: String, trim: true },
    fromto: { type: Array, default: [], required: true },
    removetoquery: { type: Array, default: [], required: true },
    lastactivation: { type: Date },
    nextactivation: { type: Date },  
    parse: { type: Boolean, default: false, required: true },  
    vigiaid: { type: String },
    vigiaenabled: { type: Boolean, default: false },  
    ftphost: { type: String },
    ftpport: { type: String },
    ftpuser: { type: String },
    ftppass: { type: String },
    ftpfile: { type: String },
    autorization: { type: String },
    authuser: { type: String },
    authpass: { type: String },
    authtoken: { type: String },
    usearia2c: { type: Boolean, default: false, required: true },  
    useftp: { type: Boolean, default: false, required: true },
    enabled: { type: Boolean, default: true, required: true },  
    inprogress: { type: Boolean, default: false, required: true }, 
    total: { type: Number, default: 0, required: true }, 
    createat: { type: Date, required: true, default: Date.now },
    createuser: { type: Object },
    auto: { type: Boolean, default: false, required: true },
}, { 
    collection: "feeds",
    timestamps: true
}));
